controller_joint_names: ['joint1_1', 'joint1_2', 'joint1_3', 'joint1_4', 'joint2_1', 'joint2_2', 'joint2_3', 'joint2_4', 'joint3_1', 'joint3_2', 'joint3_3', 'joint3_4', 'joint4_1', 'joint4_2', 'joint4_3', 'joint4_4', ]
